# Generated by Django 2.1.5 on 2019-01-20 22:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20190120_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='users_reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 1, 43, 28, 895946)),
        ),
    ]
