# Generated by Django 2.1.5 on 2019-01-21 12:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20190121_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, related_name='user_reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 15, 39, 57, 212370)),
        ),
    ]
