# Generated by Django 2.1.5 on 2019-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190131_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
