# Generated by Django 2.1.5 on 2019-01-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
