# Generated by Django 2.1.5 on 2019-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescr',
            name='period',
            field=models.IntegerField(choices=[(0, 'Сегодня'), (1, '7 дней'), (2, '14 дней'), (3, 'Месяц')], default=3),
        ),
    ]
