# Generated by Django 2.1.5 on 2019-01-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20190123_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
