# Generated by Django 2.1.5 on 2019-01-22 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20190122_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('priority', models.IntegerField(choices=[(-1, 'red'), (0, 'yellow'), (1, 'white')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (0, 'Uncompleted')], default=0)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='to_do.Project'),
        ),
    ]
