# Generated by Django 2.1.5 on 2019-02-09 14:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(blank=True, default=datetime.date(2019, 2, 9))),
                ('end_date', models.DateField(blank=True, default=datetime.date(2019, 2, 2))),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='searchdate',
            unique_together={('start_period', 'end_date')},
        ),
    ]
