# Generated by Django 2.1.5 on 2019-02-01 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=150)),
                ('published', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date_of_return', models.DateField(blank=True, default=datetime.date(2019, 2, 16))),
                ('status_of_book', models.IntegerField(choices=[(1, 'The book is on hands'), (0, 'The book is in library'), (-1, 'Need to return the book')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_information', to='core.BookInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.PositiveIntegerField()),
                ('bookcase', models.PositiveIntegerField()),
                ('shelf', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='person_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='core.Person'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Genre'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_information', to='core.Location'),
        ),
    ]
