# Generated by Django 2.1.5 on 2019-02-23 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190202_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genre_info', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_of_return',
            field=models.DateField(blank=True, default=datetime.date(2019, 3, 9)),
        ),
        migrations.AlterUniqueTogether(
            name='bookinfo',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('lastname', 'firstname', 'birthday')},
        ),
    ]
