# Generated by Django 2.1.4 on 2019-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=120)),
                ('person_subscription', models.CharField(max_length=120)),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('date_of_return', models.DateField(auto_now=True)),
                ('status_of_book', models.IntegerField(choices=[(0, 'The book is on hands'), (1, 'The book is in library')], default=1)),
            ],
        ),
    ]
