# Generated by Django 2.1.4 on 2019-01-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0002_auto_20190102_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=150)),
                ('published', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.PositiveIntegerField()),
                ('bookcase', models.PositiveIntegerField()),
                ('shelf', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='status_of_book',
            field=models.IntegerField(choices=[(1, 'The book is on hands'), (0, 'The book is in library')], default=1),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HelperCode.Genre'),
        ),
    ]
