# Generated by Django 2.1.5 on 2019-02-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='genre',
        ),
    ]
