# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='udpated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
