# Generated by Django 2.1.4 on 2019-01-02 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_of_issue',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_of_return',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='books',
            name='status_of_book',
            field=models.IntegerField(choices=[('On hands', 'The book is on hands'), ('In library', 'The book is in library')], default='On hands'),
        ),
    ]
