# Generated by Django 2.1.4 on 2019-01-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0003_auto_20190103_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_information', to='HelperCode.Location'),
            preserve_default=False,
        ),
    ]
