# Generated by Django 2.1.4 on 2019-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0004_bookinfo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status_of_book',
            field=models.IntegerField(choices=[('ON_HANDS', 'The book is on hands'), ('IN_LIBRARY', 'The book is in library'), ('ALARN', 'Need to return the book')]),
        ),
    ]
