# Generated by Django 2.1.4 on 2019-01-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0005_auto_20190103_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='person_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='HelperCode.Person'),
        ),
        migrations.AlterField(
            model_name='books',
            name='status_of_book',
            field=models.IntegerField(choices=[(1, 'The book is on hands'), (0, 'The book is in library'), (-1, 'Need to return the book')]),
        ),
    ]
