# Generated by Django 2.1.4 on 2019-01-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0006_auto_20190103_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_information', to='HelperCode.Location'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_information', to='HelperCode.BookInfo'),
        ),
    ]
