# Generated by Django 2.1.4 on 2019-01-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelperCode', '0007_auto_20190103_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_of_return',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 19)),
        ),
    ]
