# Generated by Django 2.1.5 on 2019-02-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
    ]
